baseURL: "/"
languageCode: "en-us"

title: "Apache Local Community"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Apache Local Community"
  description: "Your local open source community"
  images: 
    - "images/ALC-Icon.png"

  logo: "images/ALC.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    linkedin: "https://www.linkedin.com/company/alcindorechapter/"
    twitter: "https://twitter.com/ALCInitiative"
    facebook: "#"
  location:

  contact:
    - "dev@community.apache.org"

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Chapters"
      url: "/chapters"
      weight: 2

    - name: "Past Events"
      url: "/#"
      weight: 3

    - name: "Upcoming Events"
      url: "/#"
      weight: 4

    - name: "News"
      url: "https://news.apache.org/"
      weight: 5

  buttons:
    - name: "GSoC"
      url: "https://community.apache.org/gsoc/"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "ALC Events"
      url: "/blog"
      weight: 1

    - name: "ASF"
      url: "https://apache.org/"
      weight: 2

    - name: "Community"
      url: "https://community.apache.org/"
      weight: 3

    - name: "Sponsor"
      url: "https://www.apache.org/foundation/sponsorship"
      weight: 4

    - name: "Projects"
      url: "https://projects.apache.org/"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
